eye:
  wine_env: 'WINEDLLOVERRIDES="dxgi,d3d11=b"'
  wine_prefix: '~/.wine-dxvk'
  wine_cmd: '~/.wine-dxvk/drive_c/Program Files (x86)/Steam/Steam.exe'
  wine_cmd_args: '-applaunch 91700'
  notes: 'working with wine-3.10 (Staging)/dxvk-0.54'
overwatch:
  wine_prefix: '~/.wine-dxvk'
  wine_cmd: '/media/Games/GamesLinux/dxvk/Games/Overwatch/Overwatch.exe'
  notes: 'working with wine-3.10 (Staging)/dxvk-0.54. use wine built-in for dxgi/d3d11 during install'
overwatch-launcher:
  wine_env: 'WINEDLLOVERRIDES="dxgi,d3d11=b"'
  wine_prefix: '~/.wine-dxvk'
  wine_cmd: '/media/Games/GamesLinux/dxvk/Games/Overwatch/Overwatch Launcher.exe'
  notes: 'working with wine-3.10 (Staging)/dxvk-0.54. use wine built-in for dxgi/d3d11 during install'
warframe:
  wine_env: 'DXVK_HUD=fps'
  wine_prefix: '~/.wine-dxvk'
  wine_cmd: '~/.wine-dxvk/drive_c/Program Files (x86)/Steam/Steam.exe'
  wine_cmd_args: '-applaunch 230410'
  notes: 'working with wine-3.10 (Staging)/dxvk-0.54'
witcher-3:
  wine_env: 'DXVK_HUD=fps'
  wine_prefix: '~/.wine-dxvk'
  wine_cmd: '~/.wine-dxvk/drive_c/Program Files (x86)/Steam/Steam.exe'
  wine_cmd_args: '-applaunch 292030'
  notes: 'working with wine-3.10 (Staging)/dxvk-0.54'
