example-app:
  pre_cmd:
    - 'echo pre cmd'
    - 'echo pre cmd 2'
  wine_prefix: '~/.wine-dxvk'
  wine_env:
    - 'DXVK_HUD=fps'
    - 'ANOTHER=TEST_ENV'
  wine_cmd: '~/.wine-dxvk/drive_c/windows/system32/ping.exe'
  wine_cmd_arg: 'google.com'
  post_cmd:
    - 'echo post cmd'
  notes: 'this is an example app'
example-app-2:
  wine_prefix: '~/.wine-dxvk'
  wine_cmd: '~/.wine-dxvk/drive_c/windows/system32/ping.exe'
  wine_cmd_arg: 'google.com'
  notes: 'this is an example app'
